### PR TITLE
translate readme to zh-hant

### PR DESCRIPTION
**Pull request by KAIYOHUGO**
ヾ(•ω•`)o

### CODE REVIEW

**Comment by rocksdanister** [comment]
Is there any native way to add multiple languages to github readme without adding a link at the top? 🤔

**Comment by KAIYOHUGO** [comment]
> Is there any native way to add multiple languages to github readme without adding a link at the top? 🤔

After search, there didn't have any native way to add multiple language to readme or wiki  ¯\\\_(ツ)\_/¯

**Comment by rocksdanister** [comment]
Okay.
I will merge later along with the next update!

**Comment by Stevewsw** [comment]
> Okay.
> I will merge later along with the next update!

great!!!

**Comment by rocksdanister** [comment]
Maintaining multiple readme will be difficult, so I am closing this pr.

**Pull request closed without merging**
