### PR TITLE
Add Lively Properties JSON Schema

### PR DESCRIPTION
**Pull request by dejohansson**
- Not sure where the schema should be placed so I put it in the root folder for now.
- I haven't been able to figure out what the "tick" property on the slider setting does so I left its description empty for now.

### CODE REVIEW

**Comment by dejohansson** [comment]
This adds the JSON schema discussed in #1468

**Comment by rocksdanister** [comment]
maybe its better to create a `schemas` folder in root and move it ther?
"tick" was used to show intervals in slider UI, no longer being used now.

**Comment by dejohansson** [comment]
> maybe its better to create a schemas folder in root and move it ther?

Sounds good 👍 It's moved now.

> "tick" was used to show lines in the UI for step, no longer being used now.

Alright, I removed the property from the schema. I assume it should also be removed from the wiki ([here](https://github.com/rocksdanister/lively/wiki/Web-Guide-IV-:-Interaction#to-set-it-up) and [here](https://github.com/rocksdanister/lively/wiki/Web-Guide-IV-:-Interaction#slider)) to mitigate confusion in the future?

**Comment by rocksdanister** [comment]
Looks good 🥳

**Pull request merged**
