### PR TITLE
Adding a shuffle feature

### PR DESCRIPTION
**Pull request by ayabusa**
# Why adding a shuffle feature ?
The first time I installed Lively I wanted to automatically switch to new random wallpaper after some time, but I could not. So I decided to add this feature myself as I feel it's a crucial one. For the user it adds a new button which open a little menu where he can choose to enable/disable the feature and change the delay (see screenshot). After that, the user can do something else on his computer and the wallpaper will automatically change after some time, which I find really convenient :)

image

# From a technical aspect.
The core of the shuffle loop is located in the TimerService.cs file, the loop is created at the begining, if the setting DoRandomWallpaper is set to true and using the TimeToChangeWallpaper setting as the intervall. Once Lively is launched the loop can be enabled/disabled/modified using the UI (ShuffleView and ShuffleViewModel).

That's it, I hope you will accept this feature as I feel it is a crucial element for such a program :)

### CODE REVIEW

**Comment by rocksdanister** [comment]
Good work!

Normally for pull requests it is recommended to start an issue/discussion to plan how to implement; I'll keep this one open.. 
Will take a look when I am free.. currently busy making a weather app ^_^

**Comment by ayabusa** [comment]
Thanks for your reply,
And sorry for not having started an issue/discussion, I will know for next time !
I’m available if you need anything that would help the implementation of this feature :D

**Comment by 0xDeadcell** [comment]
Any update on getting this merged? I'd love to see this feature.

**Comment by rocksdanister** [comment]
Wallpaper stealing focus on start was one of the reason playlist never got implemented, now that it is fixed can look into adding this feature next update.

For the time being you can write scripts to implement playlist:
https://github.com/rocksdanister/lively/wiki/Command-Line-Controls#python

**Comment by forzayt** [comment]
hwwy Im intrested in this project

**Comment by yaseno2186** [comment]
Any news for this feature? ,  I was going to create such  the same one ,  but I saw his, and I really liked it. But my idea was a little bit different , and that was to do a random wallpaper on the rainy theme. , liked to change the wallpaper randomly from a file, but if this feature gets merged, I will appreciate it.

**Comment by anagggfz0** [comment]
Niceee

**Comment by JackMcHudson** [comment]
Can anyone help me on how to implement this code totally beginner in coding

**Comment by rocksdanister** [comment]
@JackMcHudson 
There is already a built in random wallpaper command, there is no need to compile the application: 
https://github.com/rocksdanister/lively/wiki/Command-Line-Controls#set-wallpaper

A simple batch script and with task scheduler or Autohotkey should work:
https://www.youtube.com/watch?v=iEb5DVMz3Ds

**Comment by rocksdanister** [comment]
Sorry for the delay.
After reviewing the PR, I’ve concluded that it doesn’t align with the planned approach for implementing this feature. As mentioned earlier, it’s generally best to start with an issue or discussion to ensure alignment on the implementation plan. You can find more details in the [contributor guidelines.]( https://github.com/rocksdanister/lively/wiki/Contributing-Guidelines)

**Comment by JackMcHudson** [comment]
@rocksdanister 
Huge thanks for your help. Never did any type of script or anything like this before but you really helped me with the vid.
But 2 problems. First the volume script for some reason doesn't work. All the other script works fine only the volume doesn't get any respond. Secondly how can I add a blur effect when the wallpapers are changing. Because now the screen just blacks out for half a second and then changes into another wallpaper. Still pretty cool but do you have any suggestions for this.
Again huge thanks 👍👍

**Comment by rocksdanister** [comment]
Don't ping, I have notification enabled throughout the repo.

This is not the place for troubleshooting this, create a new discussion instead.

**Pull request closed without merging**
