### PR TITLE
Add a reload wallpapers button (tray menu) #1822

### PR DESCRIPTION
**Pull request by Ju1-js**
### Initial Problem
When I was developing html wallpapers for lively awhile back, I found that I had no easy way to reload/refresh the wallpapers without the app open.
### Proposed solution
Adds a "reload wallpapers" button to the tray menu, only in english for now, other languages will have to be translated.
### Alternatives
I used to just leave the app open and right click -> set as wallpaper to reload it like: #1689 

*Ps. I came back to this though when I was looking through issues and found #1822*

### CODE REVIEW

**Comment by Ju1-js** [comment]
When I was implementing this addition, there were 2 functions that seemed to work, [desktopCore.ResetWallpaper](https://github.com/rocksdanister/lively/blob/9692ec07f3468bd9e337f11f37ce5c36282504ec/src/Lively/Lively/Core/WinDesktopCore.cs#L576) and [desktopCore.RestoreWallpaper](https://github.com/rocksdanister/lively/blob/9692ec07f3468bd9e337f11f37ce5c36282504ec/src/Lively/Lively/Core/WinDesktopCore.cs#L827C33-L827C33). When testing the two, surprisingly [desktopCore.ResetWallpaper](https://github.com/rocksdanister/lively/blob/9692ec07f3468bd9e337f11f37ce5c36282504ec/src/Lively/Lively/Core/WinDesktopCore.cs#L576) seemed to be a bit more stable. Which one should be used in this context?

**Comment by rocksdanister** [comment]
I don't feel there is a need for separate UI since `SetWallpaper` command to reload:
https://github.com/rocksdanister/lively/wiki/Command-Line-Controls#set-wallpaper

Also ResetWallpaper shutsdown everything and restarts, its not meant to be used to reload wallpaper.

**Comment by Ju1-js** [comment]
> I don't feel there is a need for separate UI since `SetWallpaper` command to reload: [rocksdanister/lively/wiki/Command-Line-Controls#set-wallpaper](https://github.com/rocksdanister/lively/wiki/Command-Line-Controls#set-wallpaper)
>
> Also ResetWallpaper shutsdown everything and restarts, its not meant to be used to reload wallpaper.

New [commit](https://github.com/rocksdanister/lively/pull/1917/commits/a5b4ee884e50d33724de76e3536b18d98fc1b7f8) essentially duplicates [desktopCore.ResetWallpaper](https://github.com/rocksdanister/lively/blob/9692ec07f3468bd9e337f11f37ce5c36282504ec/src/Lively/Lively/Core/WinDesktopCore.cs#L576C26-L576C26), but doesn't terminate everything.

I'll also look into simply firing a command at lively on save in terms of the workflow, but I think I could be nice to have a dedicated button for reloading things.

**Comment by Ju1-js** [comment]
You're probably right in assuming that most wallpapers aren't going to need to be reloaded, it would mostly be html based ones.
However I feel it could be nice for anyone wanting to restore their html wallpaper to it's original state without opening the ui.

**Comment by rocksdanister** [comment]
Similar to random just added a `reload` wallpaper command for `setwp` to make it easy https://github.com/rocksdanister/lively/commit/41af1d766e1756a0c894097c544fe7e334be0164

Along with future hotkey support which will let users register custom lively commandline commands directly: https://github.com/rocksdanister/lively/issues/665

I feel this is better and more versatile than adding too many options in the interface, therefore I am closing this.

**Pull request closed without merging**
